### ISSUE TITLE
When trying to grant access via authorize an instagram app, it returns 500 error

### ISSUE THREAD

**Issue by celcoder** [codingbadger/instant-tokens.com#20]
Steps taken:
1. click the authorized Instagram application
2. loads up Instagram to allow access page
3. After clicking allow permissions, it gets redirected back to Instant-token website and the following error is thrown.  

Can you provide any context in regards to this error ?

{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "https://ig.instant-tokens.com/tokens/authorise?code=AQAew2_T36hArF8G1JyBnRSsZjH8BCEU6NNBkKV80o45FbvNfn6kHzDyTISRzEvFJ2X_x4sUVq9y1uMfl_yue9ABLnZNLlQyZ3k_vgl-1uaxNyDByZUmHDvFG9s2QWPReS-GMglrArQU0wfYTC4HiufvT_0pdgJI6mzqQzTMFZ2N9MoKlbi-tgCwvjnhQX68p4yGtso55cLoUncWJtjnT-6KrAV8w3Egr-4DH6kHpTmsog",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://ig.instant-tokens.com/tokens/authorise?code=AQAew2_T36hArF8G1JyBnRSsZjH8BCEU6NNBkKV80o45FbvNfn6kHzDyTISRzEvFJ2X_x4sUVq9y1uMfl_yue9ABLnZNLlQyZ3k_vgl-1uaxNyDByZUmHDvFG9s2QWPReS-GMglrArQU0wfYTC4HiufvT_0pdgJI6mzqQzTMFZ2N9MoKlbi-tgCwvjnhQX68p4yGtso55cLoUncWJtjnT-6KrAV8w3Egr-4DH6kHpTmsog: 500 OK",
  "error": {
    "message": "Internal Server Error"
  }
}

**Comment by kamilmedrala** [comment]
Same started happening to me today

**Comment by codingbadger** [comment]
This looks to have been an issue with the Instagram/Facebook API. The code was failing when attempting to convert the short lived token for a long lived token. I have checked the IG/FB API and nothing has changed since implementation but I can see it was returning an error yesterday. It doesn't provide any indication as to what the problem was though.

I have tested it today using a few different account it all looks good now. 

Let me know if you are still having problems

Thanks!

Barry
